// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Logging/LogMacros.h"

/** 战斗框架统一日志分类（独立定义，不依赖 CommonUtility） */

CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatManager, Log, All);
CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatCoordinator, Log, All);
CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatDataStore, Log, All);
CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatComponent, Log, All);
CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatAI, Log, All);
CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatInput, Log, All);
CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatScenePoint, Log, All);
CATCOMBATFRAMEWORK_API DECLARE_LOG_CATEGORY_EXTERN(LogCatCombatHUD, Log, All);
