// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

/**
 * 战斗框架内部使用的 GameplayTag（独立定义，不依赖 CommonUtility / CommonGameplayTags）。
 *
 * 由源项目移植而来，语义保持一致：
 *  - State.Turn.*        角色回合状态机状态 Tag
 *  - Ability.Combat.*    战斗加入/离开 Ability Tag
 */
namespace CatCombatGameplayTags
{
	// 角色回合状态（State.Turn.*）
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_TURN_IDLE);
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_TURN_SELECTING);
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_TURN_ACTING);
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_TURN_DEFENDING);
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_TURN_DEFERRED);
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_TURN_ACTED);

	// 战斗 Ability（Ability.Combat.*）
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBAT_JOIN);
	CATCOMBATFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBAT_LEAVE);
}
